### ISSUE TITLE
Possible python 2.7 support

### ISSUE THREAD

**Issue by BodhiSukha** [iyzico/iyzipay-python#15]
Would you please consider making this code python 2.7 compatible? 

Our code base is large and using python 2.7, and it's not possible for us to migrate to 3.x any time soon. Considering your old API is going to be obsolete by July, it would be great if this API was backward (python 2.7) compatible. 

At a glance, I can see one main import `import http.client` which would prevent it from being backward compatible, and it has a relatively easy solution:

1) Adding a pip requirement for `future` library 
2) Adding these two lines at the top of iyzico_resource.py 
```
from future import standard_library
standard_library.install_aliases()
```

I'll check and try to spot other compatibility issues. 

Please let us know what you think.

**Comment by ademirsoy** [comment]
Hi Sukha,

Thanks for the feedback. Python 2.7 Support is a work in progress and should be released in about a week.

Best,
Ali

**Comment by yyenigun** [comment]
This issue is duplicated. It is already opened before:

https://github.com/iyzico/iyzipay-python/issues/3
