### ISSUE TITLE
Documentation - implementation mismatch 

### ISSUE THREAD

**Issue by altunyurt** [iyzico/iyzipay-python#27]
Documents state that the conversationId parameter is optional, but it's absence breaks the code

    File "/virtenvs/flask/lib/python2.7/site-packages/iyzipay/iyzipay_resource.py", line 216, in to_pki_string
        pki_builder = iyzipay.PKIBuilder(self.resource_pki(request))
    File "/virtenvs/flask/lib/python2.7/site-packages/iyzipay/iyzipay_resource.py", line 68, in resource_pki
        return 'locale=' + request.get('locale') + ',conversationId=' + request.get('conversationId') + ','
    TypeError: cannot concatenate 'str' and 'NoneType' objects

Supplying an empty string value works.

**Comment by altunyurt** [comment]
https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu

mentions CheckoutFormAuth, but no such class exists. 

    checkout_form_auth = iyzipay.CheckoutFormAuth()

**Comment by dogukankotan** [comment]
:+1:

**Comment by sotuzun** [comment]
We are working on it. Thanks @altunyurt @dogukankotan

**Comment by sotuzun** [comment]
@altunyurt Your contributions are welcome for optional conversation id.

**Comment by electrocoder** [comment]
Merhaba. Hata mesajı :     
self.request_string = self.request_string + key + "=" + str(value) + ","
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 10: ordinal not in range(128)
