### ISSUE TITLE
Fiyat parametrelerinde ondalık kısım - geçersiz imza

### ISSUE THREAD

**Issue by kurtulussahin** [iyzico/iyzipay-python#35]
Fiyat parametrelerinde ondalık kısım için 2 haneden fazla girildiğinde "geçersiz imza" hatası alınıyor.

**Comment by dogukankotan** [comment]
Sandbox ortamında geçersiz imza hatası alıyorum. Aynı kod gerçek ortamda çalışıyor. Test kartlarıyla ilgili bir sorun mu var acaba?

**Comment by dogukankotan** [comment]
Sorunu buldum. gsmNumber boş olmaması gerekiyormuş

**Comment by kurtulussahin** [comment]
Çok teşekkürler @dogukankotan.
Aynı şekilde test ederek, python kütüphanesi için geliştirme listesine ekleyeceğiz.

**Comment by sodaliAyran** [comment]
Geçersiz imza problemi düzeltildi mi? Ben de aynı problem ile karşı karşıyayım.

**Comment by bernaderya1** [comment]
Selamlar @kurtulussahin, “Geçersiz imza” hatası istek yapısı doğru iletilmediğinde ya da parametre tipleri yanlış gönderildiğinde alınmaktadır.
Güvenlik anahtarı (secret key) yanlış girildiğinde alınmaktadır, güvenlik anahtarının başında veya sonunda bir boşluk olmadığını kontrol edebilir misiniz? 
Eğer karakter encoding olarak utf-8 kullanılmamışsa bu hata oluşacaktır. Karakter encoding olarak utf8 kullandığınızı kontrol edebilir misiniz?    
Eğer parametreler uygun formatta girilmemişse de bu hata alınmaktadır. Girmiş olduğunuz parametrelerin formatını tekrardan kontrol edebilir misiniz?
Ek olarak, price parametresi null olarak gönderilemez, istek yapısı düzeltildiğinde, eğer price parametresi null veya 0 (sıfır) olarak gönderilirse, sistem Fiyat bilgisi sıfırdan büyük olmalıdır hatası dönecektir.
