### ISSUE TITLE
initialize_checkout_form  - geçersiz imza

### ISSUE THREAD

**Issue by erhanturan** [iyzico/iyzipay-python#47]
Selamlar,

Samples kısmındaki [initialize_checkout_form.py](https://github.com/iyzico/iyzipay-python/blob/master/samples/initialize_checkout_form.py) geçersiz imza hatası veriyor: 

{"status":"failure","errorCode":"1000","errorMessage":"Geçersiz
imza","locale":"tr","systemTime":1572376824669,"conversationId":"123456789"}

callback adresini de değiştirdim ama hata gelmeye devam ediyor. apikey, secretkey ve url girilmiş durumda. sandbox üstünde deniyorum... Aynı Key'ler ile iyzipay.Payment() ise çalışıyor. 

Çözüm önerisi varsa dinlemek isterim.

Teşekkürler.

**Comment by erhanturan** [comment]
Çözümü buldum. Request içindeki ` 'debitCardAllowed': True` key'inin kaldırılması gerekiyor. 

Ödeme formu [dökümantasyonunda](https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-baslatma) bulunan Python örneği ile karşılaştırınca gördüğüm ilk fark buydu. github içindeki form örneğinin düzeltilmesi gerekiyor.

**Comment by byasarcse** [comment]
Merhabalar @erhanturan,

İlgili parametre sample'dan kaldırılmıştır.
