### ISSUE TITLE
5078 - SubMerchantKeylere ait alt üye işyerleri sistemde bulunamadı

### ISSUE THREAD

**Issue by electrocoder** [iyzico/iyzipay-python#50]
Merhaba, sandbox ile çalışırken bu hatayı alıyorum. Dökümanlarda ve örnek kodlarda çözümü bulamadım.

**Comment by furkanyilmazx** [comment]
Merhaba,

Tum ornekler icin `options` dictionary' sindeki `api_key` ve `secret_key` i iyzico uye isyeri panelinden ayarlar sayfasina girerek aldiginiz api ve secret key ile guncellemeniz gerekmekte. 

```python
import iyzipay

options = {
    'api_key': YOUR_API_KEY,
    'secret_key':  YOUR_SECRET_KEY,
    'base_url': IYZIPAY_BASE_URL(e.g. `sandbox-api.iyzipay.com`)
}
```

**Comment by ShopskaSalad** [comment]
Selamlar @electrocoder,
İlk olarak, ilgili submerchant sisteminizde bulunduğundan emin olunması gerekmektedir, aslında hata doğrudan bunu işaret ediyor.
Sonrasında sizlerden ricamız bizimle request logları ya da ilgili kod kısımlarını paylaşmanız, böylece inceleyip hızlıca çözüm oluşturabiliriz.
Mutlu kodlu yıllar 🎄 ✌️

**Comment by byasarcse** [comment]
Zaman aşımından konuyu kapatıyoruz.
