### ISSUE TITLE
Servisten donen parametrelere nasil erisilecek bununla ilgili bir ornek ya da kaynak bulamadim, HTTPResponse objesi donuyor? 

### ISSUE THREAD

**Issue by rufaidemir** [iyzico/iyzipay-python#52]

**Comment by celaltas** [comment]
content = checkout_form_initialize_response.read().decode('utf-8')
json_content = json.loads(content)
print(type(json_content))
print(json_content["checkoutFormContent"])

**Comment by ShopskaSalad** [comment]
The issue has closed as there are no updates.
