### ISSUE TITLE
3dsecure esnasında conversation data decrypt edilemedi

### ISSUE THREAD

**Issue by emregeldegul** [iyzico/iyzipay-python#54]
Aynen [bu adreste](https://github.com/iyzico/iyzipay-python/blob/master/samples/create_threeds_payment.py) belirtildiği şekilde işlemi yapıyorum, ancak 

> {"status":"failure","errorCode":"5014","errorMessage":"3dsecure esnasında conversation data decrypt edilemedi","locale":"tr","systemTime":1585411513202,"conversationId":"123456789"}

Şeklinde hata dönüyor. Herhangi bir şifreleme yapmam söylenmiyor dokümantasyon üzerinde vs. Ne yapmam gerekiyor tam olarak?

Not: Birebir aynıdır.

**Comment by furkanyilmazx** [comment]
Merhaba @emregeldegul,

Dokumantasyonda `conversationData` ile ilgili soyle bir aciklama var. 

> İşlem success yani başarılı ise, iyzico tarafından o ödemeye verilen değerdir. Bütün durumlarda dolu gelmeyebilir. Eğer dolu gelirse bu parametrenin de 3D bitirme sorgusunda gönderilmesi gerekir

Oncelikle 3Ds initialize etmen gerekiyor `callbackUrl` ile ve daha sonra iyzico callback url'e odeme hakkinda basarili donus yaptiginda response da `conversationData` varsa bu parametreyi 3Ds odemeyi bitirme asamasinda request'e eklemen gerekiyor. Yani ekstra bir encryption islemine gerek yok. [3d ile Odeme](https://dev.iyzipay.com/tr/api/3d-ile-odeme) sayfasinda ayrintilar mevcut. Konuyla ilgili baska sorularin olursa sormaktan cekinme :) Iyi calismalar

(testlerde kullandigin `conversationId` leri random uretmeni tavsiye ederim)

**Comment by emregeldegul** [comment]
Evet şimdi fark ettim, tam olarak bu conversationData tam olarak hangi durumlarda dolu hangi durumlarda boş geliyor peki?

**Comment by can3ry** [comment]
Selamlar @emregeldegul bazı bankaların 3ds entegrasyonunda talep ettiği bir bilgi. işlemin geçtiği posa göre farklılık göstermektedir. Sadece dolu aldığınızda bize iletmeniz yeterlidir.

**Comment by emregeldegul** [comment]
Anladım, teşekkür ediyorum

**Comment by can3ry** [comment]
Selamlar @emregeldegul. Request body'i ve  merchant id bilginizi destek@iyzico.com'a gönderirseniz incelemekten memnuniyet duyarız.
