### ISSUE TITLE
Geçersiz imza hatası

### ISSUE THREAD

**Issue by blueromans** [iyzico/iyzipay-python#64]
Prod ortamında bazı kartlarda geçersiz imza hatası alıyorum. Kartlar internete açık limitleri normal.

**Comment by ShopskaSalad** [comment]
Selamlar @blueromans
İnceyebilmek adına kod ve kart örneği paylaşabilir misiniz?
Mutlu kodlu seneler 🎄 ✌️

**Comment by byasarcse** [comment]
Zaman aşımını dolayısı ile konuyu kapatıyoruz.
