### ISSUE TITLE
updated version is at 1.0.37 but pip is still on 1.0.32

### ISSUE THREAD

**Issue by cemavsar** [iyzico/iyzipay-python#69]
Hi,
Updated version is at 1.0.37 but pip is still on 1.0.32. I'm getting error from a concatenate process, I believe it is related. I see the code has changed.

**Comment by isik-kaplan** [comment]
```bash
pip install wheel
pip install git+https://github.com/iyzico/iyzipay-python.git@a150418dba6d0170ff7ae3772d16ac83654cb6a9
```
You can install it either like this or you can just put the second `git+...` part in your dependency manager's lock file. 

I pinned the version because at this point I don't even know if they follow semver or not.

**Comment by ataseverk** [comment]
![image](https://user-images.githubusercontent.com/39752773/210226754-83af4a6e-ee42-4738-b38b-002a7e484114.png)


> ```shell
> pip install wheel
> pip install git+https://github.com/iyzico/iyzipay-python.git@a150418dba6d0170ff7ae3772d16ac83654cb6a9
> ```
> 
> You can install it either like this or you can just put the second `git+...` part in your dependency manager's lock file.
> 
> I pinned the version because at this point I don't even know if they follow semver or not.

**Comment by byasarcse** [comment]
Hello Everyone,

PyPI libraries has been updated. Please find the version of python library histories below.
https://pypi.org/project/iyzipay/#history

Closing the issue.
