### ISSUE TITLE
Variable name in the example in the readme causes a bug when used in Django function view.

### ISSUE THREAD

**Issue by razaltcom** [iyzico/iyzipay-python#72]
In a Django function view, the function traditionally takes an argument called `request`. Like this:

```
def main(request):
   ...
```

In the example in the readme, there is a variable called `request `that overwrites it. Solvable, but takes time of the newcomer.

I propose renaming it to `payment_request`, or something.

**Comment by byasarcse** [comment]
Hello @razaltcom ,

As you know its a sample code, you can change the definition in your integration. 

Thanks and Regards,
