### ISSUE TITLE
AttributeError: module 'iyzipay' has no attribute 'PaymentAuth'

### ISSUE THREAD

**Issue by razaltcom** [iyzico/iyzipay-python#73]
Merhabalar,

https://dev.iyzipay.com/tr/api/odeme adresindeki örneği çalıştırmak istiyorum.  Aşağıdaki hatayı alıyorum. 

```
  File "C:\Users\oguz\Documents\oguz\work\razalt.com\services\repo\mysite\payments\views.py", line 165, in main
    payment_auth = iyzipay.PaymentAuth()
AttributeError: module 'iyzipay' has no attribute 'PaymentAuth'
```

Kütüphaneyi

`pip install iyzipay`

ile kurdum. Acaba dokümantasyon pip versiyonundan önde mi? Ne yapmak lazım?

**Comment by byasarcse** [comment]
Merhaba @razaltcom,

PyPI kütüphanesi son sürümde güncel durumdadır. 
Ödeme isteği iletilebilmesi için iyzipay.Payment().create() methodunu çağırabilirsiniz.

Ek sorularınız için destek@iyzico.com ile iletişime geçebilirsiniz.

Teşekkürler,
