### ISSUE TITLE
Subscription Payment Issue

### ISSUE THREAD

**Issue by seckin** [iyzico/iyzipay-python#77]
After initializing the checkout form and getting the card information from the user, I get the following error from the API:

errorCode: "5167"
errorMessage: "Ödeme isteği threeDS olmak zorundadır"
status: "failure"
systemTime: 1634850875137

This happens right after the user clicks the "Pay" button.

**Comment by BarisDev** [comment]
I have the same issue on php. Any update on this?

**Comment by byasarcse** [comment]
Hello @seckin,

This error might be related to your account settings, please reach out to destek@iyzico.com with the request-response with your merchantId.
