### ISSUE TITLE
3dsecure geçtikten sonra Üye işyerine ait ödeme kaydı bulunamadı hatası alıyorum

### ISSUE THREAD

**Issue by mertcancihan** [iyzico/iyzipay-python#78]
Aynen [bu adreste](https://github.com/iyzico/iyzipay-python/blob/master/samples/create_threeds_payment.py) belirtildiği şekilde işlemi yapıyorum, ancak 3d secure sayfasını da başarıyla geçtikten sonra

{"status"=>"failure", "error_code"=>"5087", "error_message"=>"Üye işyerine ait ödeme kaydı bulunamadı", "locale"=>"tr", "system_time"=>1635256083213, "conversation_id"=>"123456789"}

bu şekilde hata alıyorum. Bunun sebebi ve çözümü nedir?

**Comment by caneraltun** [comment]
Selamlar hatayı çözdünüzmü ?

**Comment by onurdumangoz** [comment]
> Selamlar hatayı çözdünüzmü ?

Bu sorun genellikle **ThreedsInitialize** ve **ThreedsPayment**'a gönderilen options değerlerindeki farklılıklardan oluşuyor.
ThreedsInitialize'a normal baseUrl ve API Keyleri verilmişken ThreedsPayment'a sandbox baseUrl ve API Keyleri verilmiş olabilir.

**Comment by malikmasis** [comment]
Teşekkürler, bu hatayı çözdü.
