### ISSUE TITLE
AttributeError: module 'iyzipay' has no attribute 'CheckoutFormAuth'

### ISSUE THREAD

**Issue by buurak** [iyzico/iyzipay-python#79]
`https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu`

Ödeme formu sonucunun dokümantasyondaki şekliyle alınabileceği yazıyor fakat öyle bir class mevcut değil, bunun yerine CheckoutForm ile denediğimde bu [lineda](https://github.com/iyzico/iyzipay-python/blob/a150418dba6d0170ff7ae3772d16ac83654cb6a9/iyzipay/iyzipay_resource.py#L266) 'locale' değişkeninin yollanmaması errora düşmesine sebep oluyor ama dokümantasyonda zorunluluk hayır verilmiş.
Form oluşturduktan sonra callbackurl'e gelen POST isteğinin payload'ı
```
{
    "token": "60c259bc-3be4-43f8-ae0c-2a579e105673",
    "locale": "tr"
}
```
gibi olduğunda doğru çalışıyor.

**Comment by Mahendra-vteamlabs** [comment]
Hi @buurak 

I got the same issue, but I tried the below solution and it's work for me.

`request = dict([('locale', 'tr')])
request['conversationId'] = '123456789'
request['token'] = 'token'

checkout_form_auth = iyzipay.CheckoutForm()
checkout_form_auth_response = checkout_form_auth.retrieve(request, options)`

**Comment by mahendra0401** [comment]
Hi @buurak,

I got the same issue in python integration, but I tried the below solution and it's work for me.

`request = dict([('locale', 'tr')])
request['conversationId'] = '123456789'
request['token'] = 'token'

checkout_form_auth = iyzipay.CheckoutForm()
checkout_form_auth_response = checkout_form_auth.retrieve(request, options)`

**Comment by buurak** [comment]
Hi @mahendra0401 thank you for your response, I was actually mentioning the same thing with you in Turkish anyways thanks to you we have solution in English as well.
