### ISSUE TITLE
The environment has given the SetuptoolsDeprecationWarning error while trying to setup the iyzipay package.

### ISSUE THREAD

**Issue by degerahmet** [iyzico/iyzipay-python#81]
Hey, contributors and users of iyzipay!

I got SetuptoolsDeprecationWarning on my CI (GitHub actions) environment while I was trying to install the iyzipay package with PyPI. After my research, I found the cause of the problem. The cause of the problem is the "wheel" package, so if you don't have the "wheel" package in your environment, you could probably encounter this error.

**Output of error:**

    Collecting iyzipay
      Downloading iyzipay-1.0.32.tar.gz (13 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
      error: subprocess-exited-with-error

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [52 lines of output]
        /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [8 lines of output]
        /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/setuptools/config/setupcfg.py:[50](https://github.com/actions/runs/3303925358/jobs/5452429015#step:6:51)8: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.

So, I solved this error with this lines. 
`python3 -m pip install --upgrade pip`
`pip install -U pip wheel `

> The first line is for upgrading the pip.
> The second line is for installing the package or updating the package already installed.

**Output of commands:**

    Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages (22.3)
    Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages (22.3)
    Collecting wheel
      Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
    Installing collected packages: wheel
    Successfully installed wheel-0.37.1
    Collecting iyzipay
      Downloading iyzipay-1.0.32.tar.gz (13 kB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'

Also, if the "wheel" package installation didn't work for you, you could try to update or install the "setuptools" package, like below.

`python3 -m pip install --upgrade pip`
`pip install -U pip setuptools wheel `

Have a great coding! 🤞

**Comment by ataseverk** [comment]
> Hey, contributors and users of iyzipay!
> 
> I got SetuptoolsDeprecationWarning on my CI (GitHub actions) environment while I was trying to install the iyzipay package with PyPI. After my research, I found the cause of the problem. The cause of the problem is the "wheel" package, so if you don't have the "wheel" package in your environment, you could probably encounter this error.
> 
> **Output of error:**
> 
> ```
> Collecting iyzipay
>   Downloading iyzipay-1.0.32.tar.gz (13 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'error'
>   error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully.
> │ exit code: 1
> ╰─> [52 lines of output]
>     /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
>   
> × python setup.py bdist_wheel did not run successfully.
> │ exit code: 1
> ╰─> [8 lines of output]
>     /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/setuptools/config/setupcfg.py:[50](https://github.com/actions/runs/3303925358/jobs/5452429015#step:6:51)8: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
> ```
> 
> So, I solved this error with this lines. `python3 -m pip install --upgrade pip` `pip install -U pip wheel `
> 
> > The first line is for upgrading the pip.
> > The second line is for installing the package or updating the package already installed.
> 
> **Output of commands:**
> 
> ```
> Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages (22.3)
> Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages (22.3)
> Collecting wheel
>   Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
> Installing collected packages: wheel
> Successfully installed wheel-0.37.1
> Collecting iyzipay
>   Downloading iyzipay-1.0.32.tar.gz (13 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> ```
> 
> Also, if the "wheel" package installation didn't work for you, you could try to update or install the "setuptools" package, like below.
> 
> `python3 -m pip install --upgrade pip` `pip install -U pip setuptools wheel `
> 
> Have a great coding! 🤞

Thank you very much; I spent a whole day solving this problem. 
This was the solution for the version 1.0.32. I am using an Amazon Linux docker image.
"pip install -U pip setuptools wheel"
Best,

**Comment by byasarcse** [comment]
Hello @degerahmet ,

Thank you for your comment, closing the issue. 

Have a great coding!
