### ISSUE TITLE
Is there an endpoint available in the API that allows me to retrieve payments made by a specific customer using their email address?

### ISSUE THREAD

**Issue by RodasRios** [iyzico/iyzipay-python#84]
Hello, in case the is no endpoint, I was wondering if it's possible to retrieve the email of the user associated with a payment using the payment ID. This would be useful to solve the initial problem where i need to check if a payment attached to a certain email was successful or not. If this is not currently possible, is there any other way to achieve this? Thank you for your help.

**Comment by byasarcse** [comment]
Hello @RodasRios,

There is a parameter with the name of conversationId in the request modal. Which is a matching parameter. It is an optional parameter and if you send any value in this field, iyzico will return the same value in the response. 

Then using this parameter, you can retrieve the payment result using the endpoint below. 
Endpoint: /payment/detail 

Also attaching the documents below,
https://dev.iyzipay.com/tr/api/odeme-sorgulama

You can query to get paymentResult with using PaymentConversationId.

Any type of question, please reach out to destek@iyzico.com

Thanks and Regards,
