### ISSUE TITLE
Stub dosyaları?

### ISSUE THREAD

**Issue by caner-cetin** [iyzico/iyzipay-python#89]
Kütüphanenin

```python
class CheckoutForm(IyzipayResource):
    def retrieve(self, request, options): # -> HTTPResponse:
        ...
    
    def to_pki_string(self, request): # -> str:
        ...
```

gibi metodların genel bakışını içeren stub (.pyi) dosyaları var mıdır acaba? En azından hangi fonksiyon hangi değerleri alıp ne döndürüyor görmek hoş olabilir.

**Comment by caner-cetin** [comment]
Gelen responseları class açıp marshal ederek döndürmeye karar verdim,

```
   @dataclasses
    class AddCardResponse:
        status: str
        errorCode: Optional[str]
        errorMessage: Optional[str]
        ...

    response = kart_ekleme_fonksiyonu(bir_seyler)

    print(AddCardResponse(**response))
    print(response.is_success)
```

stub dosyalarının varlığından emin olana kadar en iyi çözüm bu sanırım neyin geldiğini direkt görmek için.

**Comment by byasarcse** [comment]
Merhabalar @caner-cetin,

https://docs.iyzico.com/ döküman adresimizden, ilgili servislerimizin request-response yapılarını inceleyebilirsiniz. 

Ek sorularınız olması halinde destek@iyzico.com adresi üzerinden bizler ile iletişime geçebilirsiniz.
