### ISSUE TITLE
Iyzipay 1.0.43 not accessible through pypi.org

### ISSUE THREAD

**Issue by emmanuelgamboa09** [iyzico/iyzipay-python#94]
At the end of November, the old authentication for endpoints will be no longer supported. I believe that `1.0.43` performs the necessary upgrades with the project so that all the endpoints can migrate over to the v2 hash for authorization. But at the moment the latest version released on pypi is `1.0.42`. Is there going to be a 1.0.43 release on pypi.

Looks like the build release step failed.

**Comment by byasarcse** [comment]
Hi @emmanuelgamboa09, 

iyzipay 1.0.44 version is available on pypi. https://pypi.org/project/iyzipay/

Best Regards,
